apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  restaurantdb_url: jdbc:h2:~/restaurantdb;DB_CLOSE_ON_EXIT=FALSE
  foodcataloguedb_url: jdbc:h2:~/foodcatalogdb;DB_CLOSE_ON_EXIT=FALSE
  userdb_url: jdbc:h2:~/userdb;DB_CLOSE_ON_EXIT=FALSE
  orderdb_url: mongodb://172.23.202.112:27017/?directConnection=true
  eureka_service_address: http://eureka-0.eureka-service:8761/eureka

  
  # restaurantdb: restaurantdb
  # mysql-server: mysql-service    # The name of mysql service
  # mysql-user-username: root
  # citizen_database_url: jdbc:mysql://mysql-service:3306/citizendb
  # foodcataloguedb_url: jdbc:mysql://mysql-service:3306/foodcataloguedb
  # userdb_url: jdbc:mysql://mysql-service:3306/userdb
  # foodcataloguedb: foodcataloguedb
  # userdb: userdb
  
