apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurantapp-v1
  labels:
    app: restaurantapp-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurantapp-v1
  template:
    metadata:
      labels:
        app: restaurantapp-v1
    spec:
      containers:
        - name: restaurantapp-v1
          image: mukeshpnbe/restaurant-listing-service:26
          imagePullPolicy: Always
          ports:
            - containerPort: 9091
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: mysql-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: mysql-password
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: restaurantdb_url
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-service-v1
spec:
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
  selector:
    app: restaurantapp-v1
 
